name: satysfi-slack-bot
services:
  bot:
    build: .
    restart: always
    environment:
      SLACK_BOT_TOKEN_FILE: /run/secrets/slack_bot_token
      SLACK_SIGNING_SECRET_FILE: /run/secrets/slack_signing_secret
      BIND_ADDR: 0.0.0.0:3000
      SATYSFI_BOT_WORK_DIR: /bot/work
    ports:
      - 3000:3000
    secrets:
      - slack_bot_token
      - slack_signing_secret
    volumes:
      - work:/bot/work

volumes:
  work:

secrets:
  slack_bot_token:
    file: slack_bot_token.txt
  slack_signing_secret:
    file: slack_signing_secret.txt
